version: 2.1
orbs:
  node: circleci/node@12.9.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test