version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14.17.0-browsers
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test