version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: yarn 
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test